"""Initial migrations

Revision ID: 6e0aecaef49a
Revises: 
Create Date: 2024-09-18 19:54:28.972916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0aecaef49a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_issue', sa.String(length=200), nullable=True),
    sa.Column('study_issue', sa.String(length=200), nullable=True),
    sa.Column('improvement_suggestion', sa.String(length=200), nullable=True),
    sa.Column('event_issue', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
